In [1]:
df = spark.read.csv('/FileStore/tables/tms6y3m11489506600338/Predictor_variables_raw.csv',header=True,inferSchema=True)

In [2]:
from pyspark.sql import Row
rdd = sc.parallelize([Row(name='a', age=99, height=100), Row(name='b',age=50,height=100), Row(name='b',age=50,height=78)])

In [3]:
df1 = rdd.toDF()

In [4]:
df1.show()

In [5]:
#dropDuplicates is not in-memory operation - it will not change contents of df1
df1.dropDuplicates().show()

In [6]:
df1.show()

In [7]:
rdd.collect()

In [8]:
df1.show()

In [9]:
rdd = sc.parallelize([Row(name='a', age=50, height=100), Row(name='b',age=51,height=100), Row(name='b',age=50,height=78)])

In [10]:
rdd.toDF().dropDuplicates(['age']).show()

In [11]:
rdd = sc.parallelize([Row(name='a', age=50, height=100), Row(name='b',age=None, height=100), Row(name='b',age=50,height=78)])

In [12]:
df1 = rdd.toDF()

In [13]:
df1.dropna().show()

In [14]:
df_data = spark.read.csv('/FileStore/tables/c86o9lhs1489507726768/data_num-9d9e3.csv')

In [15]:
df_data.dropna().show()

In [16]:
df.show()

In [17]:
df =df.drop('skuid')

In [18]:
df.show()

In [19]:
help(df.na)

In [20]:
rdd = sc.parallelize([Row(name='a', age=50, height=100), Row(name='b',age=None, height=100), Row(name=None,age=50,height=78)])

In [21]:
rdd.toDF().show()

In [22]:
rdd.toDF().na.fill({'age':0, 'name':'Junk'}).show()

In [23]:
tdf = rdd.toDF()

In [24]:
tdf.show()

In [25]:
tdf.filter("age > 0").collect()

In [26]:
tdf.show()

In [27]:
def f(p):
  if p.age > 0:
    print p.name 
  
tdf.foreach(f)

In [28]:
def f(x,y):
  print x 
  print 'Awantik'
  return x
rdd.reduce(f)

In [29]:
rdd.collect()

In [30]:
df.

In [31]:
def f(r):
  if r.sales > 300:
    print r.sku
df.foreach(f)

In [32]:
sales = spark.read.csv('/FileStore/tables/esisj2031489547677702/Predictor_variables_raw.csv', header=True, inferSchema=True)

In [33]:
col = sales.select('sales')

In [34]:
help(col)

In [35]:
sales.