In [1]:
from pyspark.sql.functions import monotonically_increasing_id

In [2]:
df0 = sc.parallelize(range(2), 2).mapPartitions(lambda x: [(1,), (2,), (3,)]).toDF(['col1'])
df0.show()

In [3]:
df0.select('col1',monotonically_increasing_id().alias('id')).collect()

In [4]:
df = spark.createDataFrame(zip([],range(10))).toDF(['num'])

In [5]:
from pyspark import Row
l = [ Row(word='one'), Row(word='two'), Row(word='one')]

In [6]:
df = spark.createDataFrame(l)
df.show()

In [7]:
def f(x):
  if x.word == 'one':
    d = 1
  else:
    d = 0
  #Add name=d in each Row, Row should retain earlier content
  #x.asDict() - convert Row into dictionary
  #new Row object is created with new column contents
  return Row(name=d,**x.asDict())

df = df.rdd.map(f).toDF()

In [8]:
df.show()

In [9]:
def f(x):
  if x.word == 'one':
    d = 1
  else:
    d = 0
  return Row(inf=d,**x.asDict())
df = df.rdd.map(f).toDF()

In [10]:
df.show()

In [11]:
df.collect()

In [12]:
df = spark.createDataFrame([('2015-04-08',), ('2015-06-08',)], ['d'])

In [13]:
from pyspark.sql.functions import add_months
df.select(add_months(df.d, 1).alias('d')).show()

In [14]:
df = spark.createDataFrame([(["a", "b", "c"],), ([],)], ['data'])

In [15]:
df.show()

In [16]:
from pyspark.sql.functions import array_contains,coalesce,lit,col
df.select(array_contains(df.data, "a")).collect()

In [17]:
cDf = spark.createDataFrame([(None, None), (1, None), (None, 2)], ("a", "b"))

In [18]:
cDf.select(coalesce(cDf["a"], cDf["b"])).show()

In [19]:
cDf.select('*', coalesce(cDf["a"], lit(0.0))).show()

In [20]:
def func(**kwargs):
  print kwargs
  
func(name='awi',age=50)

db = {'age':50,'name':'awi'}

def f(name,age):
  print name,age
  
f(**db)

In [21]:
rdd = spark.sparkContext.parallelize(range(10))

In [22]:
df5 = spark.createDataFrame([(1,),(2,),(3,)],["info"])

In [23]:
df5.show()

In [24]:
from pyspark.sql.functions import acos,add_months,array_contains,coalesce

In [25]:
df5.select(acos(df5.info)).show()

In [26]:
df = spark.createDataFrame([('2015-04-08',),('2015-07-08',)], ['date'])

In [27]:

df.select('*',add_months(df.date,2).alias("after_two")).show()

In [28]:
df = spark.createDataFrame([ (['a','c'],) ,(['b','a'],)],['info 1'])

In [29]:
df.show()

In [30]:
df.select('*',array_contains(df.info1,'b').alias('does_it_have')).show()

In [31]:
df = spark.createDataFrame([(55,None),(None,77),(44,55)], ['week1','week2'])

In [32]:
df.show()

In [33]:
df.select('*', coalesce(df.week1,df.week2).alias("result")).show()

In [34]:
df.columns

In [35]:
df['info 1']

In [36]:
df = spark.createDataFrame([(5, "hello")], ['a', 'b'])
df.show()

In [37]:
from pyspark.sql.functions import format_string
df.select('*',format_string('%d-%s', df.a, df.b).alias('v')).show()

In [38]:
data = [("1", '''{"name": "Sugriv", "address": "Cambodia"}'''), ("2", '''{"name": "Bali", "address":"srilanka"}''')]

In [39]:
df = spark.createDataFrame(data,['key','value'])

In [40]:
display(df)

In [41]:
from pyspark.sql.functions import get_json_object

df.select(df.key, get_json_object(df.value,'$.name').alias("name"), get_json_object(df.value,'$.address').alias("address")).show()